# Generated by Django 4.2.2 on 2023-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Days')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
