# Generated by Django 4.2.2 on 2023-07-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0003_syllubus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursesyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=200)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purpose.course')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purpose.day')),
                ('syllabus', models.ManyToManyField(to='purpose.syllubus')),
            ],
            options={
                'verbose_name_plural': 'Course syllabus',
            },
        ),
    ]
