# Generated by Django 4.2.2 on 2023-07-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0004_coursesyllabus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesyllabus',
            options={'verbose_name_plural': 'Coursesyllabus'},
        ),
    ]
