# Generated by Django 4.2.2 on 2023-07-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0005_alter_coursesyllabus_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='syllubus',
            new_name='syllabus',
        ),
        migrations.AlterModelOptions(
            name='coursesyllabus',
            options={'verbose_name_plural': 'Course syllabus'},
        ),
    ]
